# -*- coding: utf-8 -*-
"""regressão_linear

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KwGIoD0jGSNsRLjVxZovXUxFU-SmKi7p
"""

from sklearn.linear_model import LinearRegression

x = [[1],[2],[3],[4]]
y = [2,4,6,8]

modelo = LinearRegression()
modelo.fit(x, y)

print(modelo.predict([[5]]))